// src/modules/pdf/helpers/renderFooter.ts
import { PDF_THEME as T } from "../configs/pdfTheme";
import { drawRect, applyFont } from "./pdfStyles";

export function renderFooter(
  doc: any,
  pageNum: number,
  totalPages: number,
  generatedBy?: string
) {
  const W  = T.page.width;
  const H  = T.page.height;
  const M  = T.spacing.pageMargin;
  const fY = H - 32;

  drawRect(doc, 0, fY, W, 32, T.colors.primary);
  drawRect(doc, 0, fY, W, 2,  T.colors.accent);

  applyFont(doc, 7, false, "#a0c4e8");
  const now = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });
  doc.text(`Generated: ${now} IST`, M, fY + 10);

  if (generatedBy) {
    doc.text(`Generated by: ${generatedBy}`, M, fY + 20);
  }

  applyFont(doc, 7, false, T.colors.white);
  doc.text(
    `Page ${pageNum} / ${totalPages}  |  TNPHC Inspection System — Confidential`,
    W - M - 240,
    fY + 14,
    { width: 240, align: "right" }
  );
}
