// src/modules/pdf/helpers/renderFooter.ts
import { PDF_THEME as T } from "../configs/pdfTheme";
import { drawRect, applyFont } from "./pdfStyles";

/**
 * Renders the page footer using ABSOLUTE Y positioning only.
 * Never reads or writes doc.y.
 * doc.save() / doc.restore() fully isolates all graphics state.
 */
export function renderFooter(
  doc: any,
  pageNum: number,
  totalPages: number,
  generatedBy?: string
): void {
  const W  = T.page.width;
  const M  = T.spacing.pageMargin;
  const H  = T.page.height;
  const fY = H - 32;

  doc.save();

  drawRect(doc, 0, fY, W, 32, T.colors.primary);
  drawRect(doc, 0, fY, W, 2,  T.colors.accent);

  applyFont(doc, 7, false, "#a0c4e8");
  const now = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });
  doc.text(`Generated: ${now} IST`, M, fY + 8,  { lineBreak: false });

  if (generatedBy) {
    doc.text(`Generated by: ${generatedBy}`, M, fY + 20, { lineBreak: false });
  }

  applyFont(doc, 7, false, T.colors.white);
  doc.text(
    `Page ${pageNum} / ${totalPages}  |  TNPHC Inspection System — Confidential`,
    W - M - 240,
    fY + 14,
    { width: 240, align: "right", lineBreak: false }
  );

  doc.restore();
}